name: 'Run all tests'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install ANTLR4
        run: |
          apt update
          apt install antlr4
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install deps
        run: |
          pip install --upgrade pip
          pip install antlr4-python3-runtime
          pip install bitstring
          pip install cloudpickle
          pip install holidays
          pip install kazoo
          pip install overrides
          pip install pytz
      - name: run tests
        run: |
          cd src/pyutils/datetimes && antlr ./dateparse_utils.g4
          cd ../../..
          export PYTHONPATH="$PWD/src"
          cd tests
          ./run_tests.py --unit --doctest
