name: 'Run all tests'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # The `run` key tells the job to execute a command on the runner. In this example, `npm ci` is used to install the npm software packages for the project.
      - name: Run tests
        run: cd tests && run_tests.py --all
